name: CspFix
version: 0.0.4
author: Sungguk Lim <limasdf@gmail.com>
description: Fix csp issue for chromeapp
homepage: https://github.com/sunglim/CspFixer
dependencies:
  path: any
dev_dependencies:
  unittest: any
