name: csp_fixer
version: 0.0.5
author: Sungguk Lim <limasdf@gmail.com>
description: Fix csp issue for chrome app
homepage: https://github.com/sunglim/csp_fixer
dependencies:
  path: any
dev_dependencies:
  unittest: any
executables:
  csp-fixer:
